import '../unit_model.dart';

final UnitModel unit10_0 = UnitModel(
  unitIndex: 41,
  unitName: "Enhancing Coherence and Logical Flow",
  introductionText: """
Dear all,
Welcome to Unit 10! In this unit, we will focus on enhancing the coherence and logical flow of your spoken presentations. While having great ideas is important, it’s essential to present them in an organized way, so your audience can easily follow your message. Effective speakers guide their listeners through their presentations with clear transitions, signposting, and logical sequencing. This unit includes two lessons designed to help you build rapport with your audience and refine your presentation delivery.
Let’s take a look at what you will achieve by the end of this lesson.
By the end of this lesson, students will be able to:
1.	Identify key strategies to improve coherence in spoken presentations.
2.	Use signposting language effectively to guide the audience.
3.	Structure ideas logically to maintain clarity and engagement.
4.	Apply transitions and linking phrases to create a smooth flow.
""",

  preClassActivityDescription: """
Before we begin, think about a time when you listened to a presentation that was hard to follow. What made it difficult to understand?
Reflect on and answer these questions:
1.	What challenges do you face when organizing your ideas in a presentation?
2.	Have you ever struggled to keep an audience engaged? Why?
Please share your responses in the discussion forum. 
""",

  preClassActivityUploadLink:"",

  practiceActivityDescription1: """ 
Now that you have an understanding of how to maintain the logical flow of a presentation, it's time to practice at home.

Step 1 – Choose one of the following presentation topics:
•	The benefits of regular exercise
•	The impact of social media on communication
•	How artificial intelligence is changing the workplace

Step 2 – Create a PowerPoint presentation with 3 slides covering the main points of your chosen topic. The slides should include:
1.	Slide 1 – Introduction: Introduce your topic and main message.
2.	Slide 2 – Main Points: Present 2–3 key points supporting your topic.
3.	Slide 3 – Conclusion: Summarize the main takeaways and conclude your presentation.

Step 3 – Once your slides are ready, use PowerPoint’s Presenter Coach feature to practice delivering your presentation. Here’s how to use it:
1.	In PowerPoint, go to the Slide Show tab.
2.	Click on Rehearse with Coach.
3.	Follow the instructions to begin practicing your presentation. As you speak, PowerPoint will listen to your delivery and provide real-time feedback on pacing, filler words, and clarity.
4.	After completing your practice session, review the feedback report generated by PowerPoint. It will show areas where you can improve, such as speaking too fast, too slow, or using too many filler words.

Step 4 – Take a screenshot of the best attempt of your PowerPoint Coach report, showing your performance and the feedback.

Step 5 – Upload the screenshot of your report to the portal.
""",

  practiceUploadLink:"",


  practiceActivityDescription2: """
Imagine that you are about to give a short presentation about ‘How language games help you learn English’. Follow the steps given below:
	Make your introductory speech of about 1-2 minutes. It should include:
o	Greetings
o	Introduce the topic of your presentation
o	Purpose of the presentation
o	Structure of your presentation
	Record your speech.
	Copy the link/URL of the best version of your speech and paste it here!

""",

  practiceActivityLink2:"https://www.speakpipe.com/messages",
  practiceUploadLink2:"",

  instructionsText: """
To get started, watch this short recorded lecture on structuring spoken presentations. It will introduce you to key techniques that will improve coherence and logical flow.
""",

  instructionVideoId: "8laYlyAFd0o",

  summary: """
In this lesson, we explored the importance of coherence and logical flow in spoken presentations. We discussed strategies for organizing ideas, using signposting language, and applying transitions to guide your audience. With the help of PowerPoint’s Presenter Coach, you practiced refining your delivery and received valuable feedback to improve your performance.
""",

  inClassActivity: """
We will engage in interactive activities in class to help you apply the skills you’ve learned today. These activities will include group discussions on presentation structures and opportunities to practice using transitions and signposting language. I’m excited to see you all actively participating and enhancing your presentation skills in real-time!
""",

  quizQuestions: [
    QuizQuestion(
      question: '1. What is the main purpose of using signposting language in a presentation?',
      options: [
        'a) To entertain the audience',
        'b) To introduce new vocabulary',
        'c) To guide the audience through the structure of the presentation',
        'd) To conclude the presentation',
      ],
      correctOptionIndex: 2,
    ),
    QuizQuestion(
      question: '2. Which of the following is an example of a transition phrase you can use in your presentation?',
      options: [
        'a) “I don’t know”',
        'b) “Let me explain”',
        'c) “In conclusion”',
        'd) “It’s obvious”',
      ],
      correctOptionIndex: 2,
    ),
    QuizQuestion(
      question: '3. Why is it important to have a clear structure in your presentation?',
      options: [
        'a) It makes the speaker feel confident',
        'b) It helps the audience follow your message easily',
        'c) It allows you to talk faster',
        'd) It makes the presentation longer',
      ],
      correctOptionIndex: 1,
    ),
    QuizQuestion(
      question: '4. Which of these is the most effective way to introduce the main points in a presentation?',
      options: [
        'a) Simply reading from the slides',
        'b) Using a signposting phrase like “First, I will talk about...”',
        'c) Speaking without any clear structure',
        'd) Jumping between topics',
      ],
      correctOptionIndex: 1,
    ),
    QuizQuestion(
      question: '5. Which part of your presentation is the best place to summarize your main points and conclude?',
      options: [
        'a) Introduction',
        'b) Main Points',
        'c) Conclusion',
        'd) Transitions',
      ],
      correctOptionIndex: 2,
    ),
  ],
);
